# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5c36ee1521b319d13c0932a2ccbe95cc30b444aa49641fac148ce4807ebac3588aeed096778a512886d05319bbf94c5e6959678a8de17da0da53d27f6692b67d

test:
  secret_key_base: 56de711a3d608e228219f01be0061aeb752044b38f56ba477e9b4854faddad152963f5a8b62e0e20165347ce9703abfb58f7411180fe9b03f7bef6a6f456fd1f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
